// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfS4h82m-xsleNLRlsMfrdvb0ZwDQmubg',
    appId: '1:816348960930:web:134522508d73ff488d1ffb',
    messagingSenderId: '816348960930',
    projectId: 'climas-f76be',
    authDomain: 'climas-f76be.firebaseapp.com',
    storageBucket: 'climas-f76be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-MU-kuWfkCHqdkBmBfjEn8JwGQFImXP0',
    appId: '1:816348960930:android:b8d3965a8d6f83948d1ffb',
    messagingSenderId: '816348960930',
    projectId: 'climas-f76be',
    storageBucket: 'climas-f76be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03qWkJxF8nP0Iblz0BpIssW0t-i7mwl4',
    appId: '1:816348960930:ios:25d1cd88339397db8d1ffb',
    messagingSenderId: '816348960930',
    projectId: 'climas-f76be',
    storageBucket: 'climas-f76be.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB03qWkJxF8nP0Iblz0BpIssW0t-i7mwl4',
    appId: '1:816348960930:ios:25d1cd88339397db8d1ffb',
    messagingSenderId: '816348960930',
    projectId: 'climas-f76be',
    storageBucket: 'climas-f76be.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfS4h82m-xsleNLRlsMfrdvb0ZwDQmubg',
    appId: '1:816348960930:web:c997aa11ca7bd6178d1ffb',
    messagingSenderId: '816348960930',
    projectId: 'climas-f76be',
    authDomain: 'climas-f76be.firebaseapp.com',
    storageBucket: 'climas-f76be.firebasestorage.app',
  );
}
